### PR TITLE
signature algorithm update alike eosjs pr 22

### PR DESCRIPTION
**Pull request by atticlab**
Updates to fix incompatibility with signature generation by EOS node alike pr#22 to eosjs with their test cases adopted

### CODE REVIEW

**Comment by maoueh** [comment]
@atticlab Can you provide more rationale being the changes? Link to the PR you are talking about also, I was not able to find which one exactly it is.

**Comment by StanChe** [comment]
@fproulx-eoscanada, @errows says you should review. Live from London.

**Comment by abourget** [comment]
@atticlab can you point me to the javascript test suite where you found your tests?

**Comment by abourget** [comment]
I'm really puzzled by this issue.  Seems to me that `eos-go` lines up with `eosjs`  already. See our analysis here:

https://docs.google.com/spreadsheets/d/1maGRNfE--F8oW3vXRgeM6TGAgRxqUJy8bToM6vXYb88/edit?usp=sharing

I feel that if we run multiple payloads through the different algos, we'll hit some identical and some different with all the libraries. The `0` => `1` change doesn't seem to fit with my read of the `eosjs` codebase, yet tests pass, so it would seem that for the given payload, the first iteration doesn't pass the checks.

Some clarifications regarding what "canonical" means in the case of an EOS signature: we need to distinguish the canonicality of the 4 points generated by the signature algorithm, and the "canonicality" of the serialization (encoding of the values in string form).  The former is the same on all algos, the latter is not and doesn't need to be. It is perhaps confusing because of the name `SignCanonical` used to issue such a signature.  The canonicality is a bit deeper, and the serialization is *not* canonical (in the sense that it will always serialize to the same characters).  The name `SignCanonical` is abusive.

Some people will bring up the risk of transaction malleability, but that isn't the concern here, for a few reasons:
* The signature covers everything that is hashed in a transaction ID.  You can't modify a field in the transaction, and have the signature still be valid.
* Nothing (afaik) relies on the assumption that the serialized signature be deterministic for a given privkey + payload tuple.
* The concern of RFC6979 (which is the piece tackled by this PR and these discussions) is to avoid requiring a high-quality source of randomness. `nodeos` however will accept signatures that aren't fully RFC6979.  The concern here is therefore to make sure the nonce is of high quality.

So my question is: does this patch improve the quality of the nonce, or is it just to be aligned with `eosjs` (which seems arbitrary to me, why not choose `nodeos`, `keosd` or another implementation) ?

It is however our goal to line up with RFC6979 .. but the EOS ecosystem is still a bit scattered in that sense.

**Comment by maoueh** [comment]
Closing due to inactivity, feel free to ask for a re-open if you still requires some changes from this PR.

**Pull request closed without merging**
