### PR TITLE
add setter for updating public key compatible prefix

### PR DESCRIPTION
**Pull request by blockpane**
Fixes an issue where the pubKeyReaderManifests map is never updated by adding a setter function.

### CODE REVIEW

**Comment by blockpane** [comment]
_This may not be how you would prefer to handle this, it may be more appropriate if PublicKeyPrefixCompat is made private and a getter is also added, happy to update it if desired_

**Comment by maoueh** [comment]
So, the lock in `NewPublicKey` was bugging me, I don't want to lock while creating new public keys. Seems overkill.

All in all, I refactored the code to not use a `map` anymore. This has the advantages that we control the ordering so that "Compat" key will be tried first, which is by far the most occurring case, so it will be faster now. 

It also removes entirely the need to update the map when the compat prefix change.

Now, I agree that a Setter is the best course of action. It makes it clear what can be updated and later on, we could update it if some inner structure needs to be updated. All other variables can then be made private.

If you are ok to rebase and do the change, I'll merge your contributions. Otherwise just tell me, I could do it also but wanted to give you the credit for the work started :)

**Comment by blockpane** [comment]
> So, the lock in `NewPublicKey` was bugging me, I don't want to lock while creating new public keys. Seems overkill.

It didn't feel right to me either, and I agree, getting rid of the map was the right way to go.

> If you are ok to rebase and do the change, I'll merge your contributions. Otherwise just tell me, I could do it also but wanted to give you the credit for the work started :)

I appreciate it, but you can go ahead and rebase, I'm swamped with other work and this PR wasn't all that substantial. 

I really appreciate you getting these changes in. I've already refactored 90% of the fio-go library and hope to have that ready soon.

**Comment by maoueh** [comment]
Fixed by f01c3864ad4eb2e5474fd787de0a034a74649ef7

**Pull request closed without merging**
