### PR TITLE
implement transaction ID func

### PR DESCRIPTION
**Pull request by fanyang1988**

### CODE REVIEW

**Comment by abourget** [comment]
How are you using this? Can you show me code that uses it?

The reason I ask is that usually the transaction is unpacked from a place which tells you the TRX id

**Comment by fanyang1988** [comment]
no found it, I pass the Transaction to other package to store or process, so need call ID() function, maybe i can change param type to TransactionWithID

**Comment by abourget** [comment]
Yes, TransactionWithID supports the different cases that we receive from the blockchain. Sometimes you *only* get an ID and not a PackedTransaction in there. I'd advise to use it instead.

There's no harm in merge this one I think, but we'll make docs clear about the edge cases.

**Comment by maoueh** [comment]
@abourget So do we merge it?

**Comment by maoueh** [comment]
Closes #31

**Pull request closed without merging**
