### PR TITLE
Fix NewPrivateKey correctly working with PVT_K1 keys

### PR DESCRIPTION
**Pull request by maxifom**
Fix NewPrivateKey correctly working with PVT_K1 keys. Added test for PVT_K1 NewPrivateKey.

### CODE REVIEW

**Comment by maoueh** [comment]
@maxifom Hey thanks! Can you fix the failing tests, I think it's simply because the old test is now wrong with the change you added and can you add a note in the https://github.com/eoscanada/eos-go/blob/develop/CHANGELOG.md file please.

I'll merge after that.

**Comment by maxifom** [comment]
@maoueh Should I create 0.10.3 in the Changelod?

**Comment by maoueh** [comment]
Add something under `Unreleased` section in `Fixed` sub-section.

**Comment by maoueh** [comment]
Do you want me to release a new version once this is merged?

**Comment by maxifom** [comment]
It would be nice, because it will allow eos.KeyBag to Import keys with PVT_K1, but I personally don't use eos-go, I am just using it as the reference to create transaction encoder to allow me to code generate type-safe actions from ABI.

**Comment by maxifom** [comment]
Added changelog.

**Comment by maxifom** [comment]
@maoueh

**Pull request merged**
